// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto

It has these top-level messages:
	GameMessage
	DropRequest
	DropResponse
	DropNotification
	ErrorRequest
	ErrorResponse
	ExitsRequest
	ExitsResponse
	ExitInfo
	GetRequest
	GetResponse
	GetNotification
	InventoryRequest
	InventoryResponse
	LoginRequest
	LoginResponse
	LogoutRequest
	LogoutResponse
	LookRequest
	LookResponse
	LookNotification
	RoomDescription
	MoveRequest
	MoveResponse
	EnterRoomNotification
	LeaveRoomNotification
	Ping
	Pong
	SayRequest
	SayResponse
	SayNotification
	TellRequest
	TellResponse
	TellNotification
	TellAllRequest
	TellAllResponse
	TellAllNotification
	WhoRequest
	WhoResponse
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// types
type GameMessage struct {
	// Types that are valid to be assigned to Inner:
	//	*GameMessage_Ping
	//	*GameMessage_Pong
	//	*GameMessage_DropRequest
	//	*GameMessage_DropResponse
	//	*GameMessage_DropNotification
	//	*GameMessage_ErrorRequest
	//	*GameMessage_ErrorResponse
	//	*GameMessage_ExitsRequest
	//	*GameMessage_ExitsResponse
	//	*GameMessage_GetRequest
	//	*GameMessage_GetResponse
	//	*GameMessage_GetNotification
	//	*GameMessage_InventoryRequest
	//	*GameMessage_InventoryResponse
	//	*GameMessage_LoginRequest
	//	*GameMessage_LoginResponse
	//	*GameMessage_LogoutRequest
	//	*GameMessage_LogoutResponse
	//	*GameMessage_LookRequest
	//	*GameMessage_LookResponse
	//	*GameMessage_LookNotification
	//	*GameMessage_MoveRequest
	//	*GameMessage_MoveResponse
	//	*GameMessage_EnterRoomNotification
	//	*GameMessage_LeaveRoomNotification
	//	*GameMessage_SayRequest
	//	*GameMessage_SayResponse
	//	*GameMessage_SayNotification
	//	*GameMessage_TellRequest
	//	*GameMessage_TellResponse
	//	*GameMessage_TellNotification
	//	*GameMessage_TellAllRequest
	//	*GameMessage_TellAllResponse
	//	*GameMessage_TellAllNotification
	//	*GameMessage_WhoRequest
	//	*GameMessage_WhoResponse
	Inner isGameMessage_Inner `protobuf_oneof:"inner"`
}

func (m *GameMessage) Reset()                    { *m = GameMessage{} }
func (m *GameMessage) String() string            { return proto.CompactTextString(m) }
func (*GameMessage) ProtoMessage()               {}
func (*GameMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isGameMessage_Inner interface {
	isGameMessage_Inner()
}

type GameMessage_Ping struct {
	Ping *Ping `protobuf:"bytes,50,opt,name=ping,oneof"`
}
type GameMessage_Pong struct {
	Pong *Pong `protobuf:"bytes,51,opt,name=pong,oneof"`
}
type GameMessage_DropRequest struct {
	DropRequest *DropRequest `protobuf:"bytes,100,opt,name=dropRequest,oneof"`
}
type GameMessage_DropResponse struct {
	DropResponse *DropResponse `protobuf:"bytes,101,opt,name=dropResponse,oneof"`
}
type GameMessage_DropNotification struct {
	DropNotification *DropNotification `protobuf:"bytes,102,opt,name=dropNotification,oneof"`
}
type GameMessage_ErrorRequest struct {
	ErrorRequest *ErrorRequest `protobuf:"bytes,110,opt,name=errorRequest,oneof"`
}
type GameMessage_ErrorResponse struct {
	ErrorResponse *ErrorResponse `protobuf:"bytes,111,opt,name=errorResponse,oneof"`
}
type GameMessage_ExitsRequest struct {
	ExitsRequest *ExitsRequest `protobuf:"bytes,120,opt,name=exitsRequest,oneof"`
}
type GameMessage_ExitsResponse struct {
	ExitsResponse *ExitsResponse `protobuf:"bytes,121,opt,name=exitsResponse,oneof"`
}
type GameMessage_GetRequest struct {
	GetRequest *GetRequest `protobuf:"bytes,130,opt,name=getRequest,oneof"`
}
type GameMessage_GetResponse struct {
	GetResponse *GetResponse `protobuf:"bytes,131,opt,name=getResponse,oneof"`
}
type GameMessage_GetNotification struct {
	GetNotification *GetNotification `protobuf:"bytes,132,opt,name=getNotification,oneof"`
}
type GameMessage_InventoryRequest struct {
	InventoryRequest *InventoryRequest `protobuf:"bytes,140,opt,name=inventoryRequest,oneof"`
}
type GameMessage_InventoryResponse struct {
	InventoryResponse *InventoryResponse `protobuf:"bytes,141,opt,name=inventoryResponse,oneof"`
}
type GameMessage_LoginRequest struct {
	LoginRequest *LoginRequest `protobuf:"bytes,150,opt,name=loginRequest,oneof"`
}
type GameMessage_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,151,opt,name=loginResponse,oneof"`
}
type GameMessage_LogoutRequest struct {
	LogoutRequest *LogoutRequest `protobuf:"bytes,160,opt,name=logoutRequest,oneof"`
}
type GameMessage_LogoutResponse struct {
	LogoutResponse *LogoutResponse `protobuf:"bytes,161,opt,name=logoutResponse,oneof"`
}
type GameMessage_LookRequest struct {
	LookRequest *LookRequest `protobuf:"bytes,170,opt,name=lookRequest,oneof"`
}
type GameMessage_LookResponse struct {
	LookResponse *LookResponse `protobuf:"bytes,171,opt,name=lookResponse,oneof"`
}
type GameMessage_LookNotification struct {
	LookNotification *LookNotification `protobuf:"bytes,172,opt,name=lookNotification,oneof"`
}
type GameMessage_MoveRequest struct {
	MoveRequest *MoveRequest `protobuf:"bytes,180,opt,name=moveRequest,oneof"`
}
type GameMessage_MoveResponse struct {
	MoveResponse *MoveResponse `protobuf:"bytes,181,opt,name=moveResponse,oneof"`
}
type GameMessage_EnterRoomNotification struct {
	EnterRoomNotification *EnterRoomNotification `protobuf:"bytes,182,opt,name=enterRoomNotification,oneof"`
}
type GameMessage_LeaveRoomNotification struct {
	LeaveRoomNotification *LeaveRoomNotification `protobuf:"bytes,183,opt,name=leaveRoomNotification,oneof"`
}
type GameMessage_SayRequest struct {
	SayRequest *SayRequest `protobuf:"bytes,190,opt,name=sayRequest,oneof"`
}
type GameMessage_SayResponse struct {
	SayResponse *SayResponse `protobuf:"bytes,191,opt,name=sayResponse,oneof"`
}
type GameMessage_SayNotification struct {
	SayNotification *SayNotification `protobuf:"bytes,192,opt,name=sayNotification,oneof"`
}
type GameMessage_TellRequest struct {
	TellRequest *TellRequest `protobuf:"bytes,200,opt,name=tellRequest,oneof"`
}
type GameMessage_TellResponse struct {
	TellResponse *TellResponse `protobuf:"bytes,201,opt,name=tellResponse,oneof"`
}
type GameMessage_TellNotification struct {
	TellNotification *TellNotification `protobuf:"bytes,202,opt,name=tellNotification,oneof"`
}
type GameMessage_TellAllRequest struct {
	TellAllRequest *TellAllRequest `protobuf:"bytes,210,opt,name=tellAllRequest,oneof"`
}
type GameMessage_TellAllResponse struct {
	TellAllResponse *TellAllResponse `protobuf:"bytes,211,opt,name=tellAllResponse,oneof"`
}
type GameMessage_TellAllNotification struct {
	TellAllNotification *TellAllNotification `protobuf:"bytes,212,opt,name=tellAllNotification,oneof"`
}
type GameMessage_WhoRequest struct {
	WhoRequest *WhoRequest `protobuf:"bytes,220,opt,name=whoRequest,oneof"`
}
type GameMessage_WhoResponse struct {
	WhoResponse *WhoResponse `protobuf:"bytes,221,opt,name=whoResponse,oneof"`
}

func (*GameMessage_Ping) isGameMessage_Inner()                  {}
func (*GameMessage_Pong) isGameMessage_Inner()                  {}
func (*GameMessage_DropRequest) isGameMessage_Inner()           {}
func (*GameMessage_DropResponse) isGameMessage_Inner()          {}
func (*GameMessage_DropNotification) isGameMessage_Inner()      {}
func (*GameMessage_ErrorRequest) isGameMessage_Inner()          {}
func (*GameMessage_ErrorResponse) isGameMessage_Inner()         {}
func (*GameMessage_ExitsRequest) isGameMessage_Inner()          {}
func (*GameMessage_ExitsResponse) isGameMessage_Inner()         {}
func (*GameMessage_GetRequest) isGameMessage_Inner()            {}
func (*GameMessage_GetResponse) isGameMessage_Inner()           {}
func (*GameMessage_GetNotification) isGameMessage_Inner()       {}
func (*GameMessage_InventoryRequest) isGameMessage_Inner()      {}
func (*GameMessage_InventoryResponse) isGameMessage_Inner()     {}
func (*GameMessage_LoginRequest) isGameMessage_Inner()          {}
func (*GameMessage_LoginResponse) isGameMessage_Inner()         {}
func (*GameMessage_LogoutRequest) isGameMessage_Inner()         {}
func (*GameMessage_LogoutResponse) isGameMessage_Inner()        {}
func (*GameMessage_LookRequest) isGameMessage_Inner()           {}
func (*GameMessage_LookResponse) isGameMessage_Inner()          {}
func (*GameMessage_LookNotification) isGameMessage_Inner()      {}
func (*GameMessage_MoveRequest) isGameMessage_Inner()           {}
func (*GameMessage_MoveResponse) isGameMessage_Inner()          {}
func (*GameMessage_EnterRoomNotification) isGameMessage_Inner() {}
func (*GameMessage_LeaveRoomNotification) isGameMessage_Inner() {}
func (*GameMessage_SayRequest) isGameMessage_Inner()            {}
func (*GameMessage_SayResponse) isGameMessage_Inner()           {}
func (*GameMessage_SayNotification) isGameMessage_Inner()       {}
func (*GameMessage_TellRequest) isGameMessage_Inner()           {}
func (*GameMessage_TellResponse) isGameMessage_Inner()          {}
func (*GameMessage_TellNotification) isGameMessage_Inner()      {}
func (*GameMessage_TellAllRequest) isGameMessage_Inner()        {}
func (*GameMessage_TellAllResponse) isGameMessage_Inner()       {}
func (*GameMessage_TellAllNotification) isGameMessage_Inner()   {}
func (*GameMessage_WhoRequest) isGameMessage_Inner()            {}
func (*GameMessage_WhoResponse) isGameMessage_Inner()           {}

func (m *GameMessage) GetInner() isGameMessage_Inner {
	if m != nil {
		return m.Inner
	}
	return nil
}

func (m *GameMessage) GetPing() *Ping {
	if x, ok := m.GetInner().(*GameMessage_Ping); ok {
		return x.Ping
	}
	return nil
}

func (m *GameMessage) GetPong() *Pong {
	if x, ok := m.GetInner().(*GameMessage_Pong); ok {
		return x.Pong
	}
	return nil
}

func (m *GameMessage) GetDropRequest() *DropRequest {
	if x, ok := m.GetInner().(*GameMessage_DropRequest); ok {
		return x.DropRequest
	}
	return nil
}

func (m *GameMessage) GetDropResponse() *DropResponse {
	if x, ok := m.GetInner().(*GameMessage_DropResponse); ok {
		return x.DropResponse
	}
	return nil
}

func (m *GameMessage) GetDropNotification() *DropNotification {
	if x, ok := m.GetInner().(*GameMessage_DropNotification); ok {
		return x.DropNotification
	}
	return nil
}

func (m *GameMessage) GetErrorRequest() *ErrorRequest {
	if x, ok := m.GetInner().(*GameMessage_ErrorRequest); ok {
		return x.ErrorRequest
	}
	return nil
}

func (m *GameMessage) GetErrorResponse() *ErrorResponse {
	if x, ok := m.GetInner().(*GameMessage_ErrorResponse); ok {
		return x.ErrorResponse
	}
	return nil
}

func (m *GameMessage) GetExitsRequest() *ExitsRequest {
	if x, ok := m.GetInner().(*GameMessage_ExitsRequest); ok {
		return x.ExitsRequest
	}
	return nil
}

func (m *GameMessage) GetExitsResponse() *ExitsResponse {
	if x, ok := m.GetInner().(*GameMessage_ExitsResponse); ok {
		return x.ExitsResponse
	}
	return nil
}

func (m *GameMessage) GetGetRequest() *GetRequest {
	if x, ok := m.GetInner().(*GameMessage_GetRequest); ok {
		return x.GetRequest
	}
	return nil
}

func (m *GameMessage) GetGetResponse() *GetResponse {
	if x, ok := m.GetInner().(*GameMessage_GetResponse); ok {
		return x.GetResponse
	}
	return nil
}

func (m *GameMessage) GetGetNotification() *GetNotification {
	if x, ok := m.GetInner().(*GameMessage_GetNotification); ok {
		return x.GetNotification
	}
	return nil
}

func (m *GameMessage) GetInventoryRequest() *InventoryRequest {
	if x, ok := m.GetInner().(*GameMessage_InventoryRequest); ok {
		return x.InventoryRequest
	}
	return nil
}

func (m *GameMessage) GetInventoryResponse() *InventoryResponse {
	if x, ok := m.GetInner().(*GameMessage_InventoryResponse); ok {
		return x.InventoryResponse
	}
	return nil
}

func (m *GameMessage) GetLoginRequest() *LoginRequest {
	if x, ok := m.GetInner().(*GameMessage_LoginRequest); ok {
		return x.LoginRequest
	}
	return nil
}

func (m *GameMessage) GetLoginResponse() *LoginResponse {
	if x, ok := m.GetInner().(*GameMessage_LoginResponse); ok {
		return x.LoginResponse
	}
	return nil
}

func (m *GameMessage) GetLogoutRequest() *LogoutRequest {
	if x, ok := m.GetInner().(*GameMessage_LogoutRequest); ok {
		return x.LogoutRequest
	}
	return nil
}

func (m *GameMessage) GetLogoutResponse() *LogoutResponse {
	if x, ok := m.GetInner().(*GameMessage_LogoutResponse); ok {
		return x.LogoutResponse
	}
	return nil
}

func (m *GameMessage) GetLookRequest() *LookRequest {
	if x, ok := m.GetInner().(*GameMessage_LookRequest); ok {
		return x.LookRequest
	}
	return nil
}

func (m *GameMessage) GetLookResponse() *LookResponse {
	if x, ok := m.GetInner().(*GameMessage_LookResponse); ok {
		return x.LookResponse
	}
	return nil
}

func (m *GameMessage) GetLookNotification() *LookNotification {
	if x, ok := m.GetInner().(*GameMessage_LookNotification); ok {
		return x.LookNotification
	}
	return nil
}

func (m *GameMessage) GetMoveRequest() *MoveRequest {
	if x, ok := m.GetInner().(*GameMessage_MoveRequest); ok {
		return x.MoveRequest
	}
	return nil
}

func (m *GameMessage) GetMoveResponse() *MoveResponse {
	if x, ok := m.GetInner().(*GameMessage_MoveResponse); ok {
		return x.MoveResponse
	}
	return nil
}

func (m *GameMessage) GetEnterRoomNotification() *EnterRoomNotification {
	if x, ok := m.GetInner().(*GameMessage_EnterRoomNotification); ok {
		return x.EnterRoomNotification
	}
	return nil
}

func (m *GameMessage) GetLeaveRoomNotification() *LeaveRoomNotification {
	if x, ok := m.GetInner().(*GameMessage_LeaveRoomNotification); ok {
		return x.LeaveRoomNotification
	}
	return nil
}

func (m *GameMessage) GetSayRequest() *SayRequest {
	if x, ok := m.GetInner().(*GameMessage_SayRequest); ok {
		return x.SayRequest
	}
	return nil
}

func (m *GameMessage) GetSayResponse() *SayResponse {
	if x, ok := m.GetInner().(*GameMessage_SayResponse); ok {
		return x.SayResponse
	}
	return nil
}

func (m *GameMessage) GetSayNotification() *SayNotification {
	if x, ok := m.GetInner().(*GameMessage_SayNotification); ok {
		return x.SayNotification
	}
	return nil
}

func (m *GameMessage) GetTellRequest() *TellRequest {
	if x, ok := m.GetInner().(*GameMessage_TellRequest); ok {
		return x.TellRequest
	}
	return nil
}

func (m *GameMessage) GetTellResponse() *TellResponse {
	if x, ok := m.GetInner().(*GameMessage_TellResponse); ok {
		return x.TellResponse
	}
	return nil
}

func (m *GameMessage) GetTellNotification() *TellNotification {
	if x, ok := m.GetInner().(*GameMessage_TellNotification); ok {
		return x.TellNotification
	}
	return nil
}

func (m *GameMessage) GetTellAllRequest() *TellAllRequest {
	if x, ok := m.GetInner().(*GameMessage_TellAllRequest); ok {
		return x.TellAllRequest
	}
	return nil
}

func (m *GameMessage) GetTellAllResponse() *TellAllResponse {
	if x, ok := m.GetInner().(*GameMessage_TellAllResponse); ok {
		return x.TellAllResponse
	}
	return nil
}

func (m *GameMessage) GetTellAllNotification() *TellAllNotification {
	if x, ok := m.GetInner().(*GameMessage_TellAllNotification); ok {
		return x.TellAllNotification
	}
	return nil
}

func (m *GameMessage) GetWhoRequest() *WhoRequest {
	if x, ok := m.GetInner().(*GameMessage_WhoRequest); ok {
		return x.WhoRequest
	}
	return nil
}

func (m *GameMessage) GetWhoResponse() *WhoResponse {
	if x, ok := m.GetInner().(*GameMessage_WhoResponse); ok {
		return x.WhoResponse
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GameMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GameMessage_OneofMarshaler, _GameMessage_OneofUnmarshaler, _GameMessage_OneofSizer, []interface{}{
		(*GameMessage_Ping)(nil),
		(*GameMessage_Pong)(nil),
		(*GameMessage_DropRequest)(nil),
		(*GameMessage_DropResponse)(nil),
		(*GameMessage_DropNotification)(nil),
		(*GameMessage_ErrorRequest)(nil),
		(*GameMessage_ErrorResponse)(nil),
		(*GameMessage_ExitsRequest)(nil),
		(*GameMessage_ExitsResponse)(nil),
		(*GameMessage_GetRequest)(nil),
		(*GameMessage_GetResponse)(nil),
		(*GameMessage_GetNotification)(nil),
		(*GameMessage_InventoryRequest)(nil),
		(*GameMessage_InventoryResponse)(nil),
		(*GameMessage_LoginRequest)(nil),
		(*GameMessage_LoginResponse)(nil),
		(*GameMessage_LogoutRequest)(nil),
		(*GameMessage_LogoutResponse)(nil),
		(*GameMessage_LookRequest)(nil),
		(*GameMessage_LookResponse)(nil),
		(*GameMessage_LookNotification)(nil),
		(*GameMessage_MoveRequest)(nil),
		(*GameMessage_MoveResponse)(nil),
		(*GameMessage_EnterRoomNotification)(nil),
		(*GameMessage_LeaveRoomNotification)(nil),
		(*GameMessage_SayRequest)(nil),
		(*GameMessage_SayResponse)(nil),
		(*GameMessage_SayNotification)(nil),
		(*GameMessage_TellRequest)(nil),
		(*GameMessage_TellResponse)(nil),
		(*GameMessage_TellNotification)(nil),
		(*GameMessage_TellAllRequest)(nil),
		(*GameMessage_TellAllResponse)(nil),
		(*GameMessage_TellAllNotification)(nil),
		(*GameMessage_WhoRequest)(nil),
		(*GameMessage_WhoResponse)(nil),
	}
}

func _GameMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GameMessage)
	// inner
	switch x := m.Inner.(type) {
	case *GameMessage_Ping:
		b.EncodeVarint(50<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Ping); err != nil {
			return err
		}
	case *GameMessage_Pong:
		b.EncodeVarint(51<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Pong); err != nil {
			return err
		}
	case *GameMessage_DropRequest:
		b.EncodeVarint(100<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DropRequest); err != nil {
			return err
		}
	case *GameMessage_DropResponse:
		b.EncodeVarint(101<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DropResponse); err != nil {
			return err
		}
	case *GameMessage_DropNotification:
		b.EncodeVarint(102<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DropNotification); err != nil {
			return err
		}
	case *GameMessage_ErrorRequest:
		b.EncodeVarint(110<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorRequest); err != nil {
			return err
		}
	case *GameMessage_ErrorResponse:
		b.EncodeVarint(111<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ErrorResponse); err != nil {
			return err
		}
	case *GameMessage_ExitsRequest:
		b.EncodeVarint(120<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExitsRequest); err != nil {
			return err
		}
	case *GameMessage_ExitsResponse:
		b.EncodeVarint(121<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ExitsResponse); err != nil {
			return err
		}
	case *GameMessage_GetRequest:
		b.EncodeVarint(130<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetRequest); err != nil {
			return err
		}
	case *GameMessage_GetResponse:
		b.EncodeVarint(131<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetResponse); err != nil {
			return err
		}
	case *GameMessage_GetNotification:
		b.EncodeVarint(132<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.GetNotification); err != nil {
			return err
		}
	case *GameMessage_InventoryRequest:
		b.EncodeVarint(140<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InventoryRequest); err != nil {
			return err
		}
	case *GameMessage_InventoryResponse:
		b.EncodeVarint(141<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InventoryResponse); err != nil {
			return err
		}
	case *GameMessage_LoginRequest:
		b.EncodeVarint(150<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginRequest); err != nil {
			return err
		}
	case *GameMessage_LoginResponse:
		b.EncodeVarint(151<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LoginResponse); err != nil {
			return err
		}
	case *GameMessage_LogoutRequest:
		b.EncodeVarint(160<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LogoutRequest); err != nil {
			return err
		}
	case *GameMessage_LogoutResponse:
		b.EncodeVarint(161<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LogoutResponse); err != nil {
			return err
		}
	case *GameMessage_LookRequest:
		b.EncodeVarint(170<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LookRequest); err != nil {
			return err
		}
	case *GameMessage_LookResponse:
		b.EncodeVarint(171<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LookResponse); err != nil {
			return err
		}
	case *GameMessage_LookNotification:
		b.EncodeVarint(172<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LookNotification); err != nil {
			return err
		}
	case *GameMessage_MoveRequest:
		b.EncodeVarint(180<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MoveRequest); err != nil {
			return err
		}
	case *GameMessage_MoveResponse:
		b.EncodeVarint(181<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.MoveResponse); err != nil {
			return err
		}
	case *GameMessage_EnterRoomNotification:
		b.EncodeVarint(182<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.EnterRoomNotification); err != nil {
			return err
		}
	case *GameMessage_LeaveRoomNotification:
		b.EncodeVarint(183<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.LeaveRoomNotification); err != nil {
			return err
		}
	case *GameMessage_SayRequest:
		b.EncodeVarint(190<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SayRequest); err != nil {
			return err
		}
	case *GameMessage_SayResponse:
		b.EncodeVarint(191<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SayResponse); err != nil {
			return err
		}
	case *GameMessage_SayNotification:
		b.EncodeVarint(192<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SayNotification); err != nil {
			return err
		}
	case *GameMessage_TellRequest:
		b.EncodeVarint(200<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TellRequest); err != nil {
			return err
		}
	case *GameMessage_TellResponse:
		b.EncodeVarint(201<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TellResponse); err != nil {
			return err
		}
	case *GameMessage_TellNotification:
		b.EncodeVarint(202<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TellNotification); err != nil {
			return err
		}
	case *GameMessage_TellAllRequest:
		b.EncodeVarint(210<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TellAllRequest); err != nil {
			return err
		}
	case *GameMessage_TellAllResponse:
		b.EncodeVarint(211<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TellAllResponse); err != nil {
			return err
		}
	case *GameMessage_TellAllNotification:
		b.EncodeVarint(212<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.TellAllNotification); err != nil {
			return err
		}
	case *GameMessage_WhoRequest:
		b.EncodeVarint(220<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WhoRequest); err != nil {
			return err
		}
	case *GameMessage_WhoResponse:
		b.EncodeVarint(221<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WhoResponse); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GameMessage.Inner has unexpected type %T", x)
	}
	return nil
}

func _GameMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GameMessage)
	switch tag {
	case 50: // inner.ping
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Ping)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_Ping{msg}
		return true, err
	case 51: // inner.pong
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Pong)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_Pong{msg}
		return true, err
	case 100: // inner.dropRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DropRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_DropRequest{msg}
		return true, err
	case 101: // inner.dropResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DropResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_DropResponse{msg}
		return true, err
	case 102: // inner.dropNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DropNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_DropNotification{msg}
		return true, err
	case 110: // inner.errorRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_ErrorRequest{msg}
		return true, err
	case 111: // inner.errorResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ErrorResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_ErrorResponse{msg}
		return true, err
	case 120: // inner.exitsRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExitsRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_ExitsRequest{msg}
		return true, err
	case 121: // inner.exitsResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ExitsResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_ExitsResponse{msg}
		return true, err
	case 130: // inner.getRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_GetRequest{msg}
		return true, err
	case 131: // inner.getResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_GetResponse{msg}
		return true, err
	case 132: // inner.getNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GetNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_GetNotification{msg}
		return true, err
	case 140: // inner.inventoryRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InventoryRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_InventoryRequest{msg}
		return true, err
	case 141: // inner.inventoryResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InventoryResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_InventoryResponse{msg}
		return true, err
	case 150: // inner.loginRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LoginRequest{msg}
		return true, err
	case 151: // inner.loginResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LoginResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LoginResponse{msg}
		return true, err
	case 160: // inner.logoutRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LogoutRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LogoutRequest{msg}
		return true, err
	case 161: // inner.logoutResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LogoutResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LogoutResponse{msg}
		return true, err
	case 170: // inner.lookRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LookRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LookRequest{msg}
		return true, err
	case 171: // inner.lookResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LookResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LookResponse{msg}
		return true, err
	case 172: // inner.lookNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LookNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LookNotification{msg}
		return true, err
	case 180: // inner.moveRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_MoveRequest{msg}
		return true, err
	case 181: // inner.moveResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(MoveResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_MoveResponse{msg}
		return true, err
	case 182: // inner.enterRoomNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(EnterRoomNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_EnterRoomNotification{msg}
		return true, err
	case 183: // inner.leaveRoomNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(LeaveRoomNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_LeaveRoomNotification{msg}
		return true, err
	case 190: // inner.sayRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SayRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_SayRequest{msg}
		return true, err
	case 191: // inner.sayResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SayResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_SayResponse{msg}
		return true, err
	case 192: // inner.sayNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SayNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_SayNotification{msg}
		return true, err
	case 200: // inner.tellRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TellRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_TellRequest{msg}
		return true, err
	case 201: // inner.tellResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TellResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_TellResponse{msg}
		return true, err
	case 202: // inner.tellNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TellNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_TellNotification{msg}
		return true, err
	case 210: // inner.tellAllRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TellAllRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_TellAllRequest{msg}
		return true, err
	case 211: // inner.tellAllResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TellAllResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_TellAllResponse{msg}
		return true, err
	case 212: // inner.tellAllNotification
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TellAllNotification)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_TellAllNotification{msg}
		return true, err
	case 220: // inner.whoRequest
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhoRequest)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_WhoRequest{msg}
		return true, err
	case 221: // inner.whoResponse
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WhoResponse)
		err := b.DecodeMessage(msg)
		m.Inner = &GameMessage_WhoResponse{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GameMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GameMessage)
	// inner
	switch x := m.Inner.(type) {
	case *GameMessage_Ping:
		s := proto.Size(x.Ping)
		n += proto.SizeVarint(50<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_Pong:
		s := proto.Size(x.Pong)
		n += proto.SizeVarint(51<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_DropRequest:
		s := proto.Size(x.DropRequest)
		n += proto.SizeVarint(100<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_DropResponse:
		s := proto.Size(x.DropResponse)
		n += proto.SizeVarint(101<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_DropNotification:
		s := proto.Size(x.DropNotification)
		n += proto.SizeVarint(102<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_ErrorRequest:
		s := proto.Size(x.ErrorRequest)
		n += proto.SizeVarint(110<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_ErrorResponse:
		s := proto.Size(x.ErrorResponse)
		n += proto.SizeVarint(111<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_ExitsRequest:
		s := proto.Size(x.ExitsRequest)
		n += proto.SizeVarint(120<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_ExitsResponse:
		s := proto.Size(x.ExitsResponse)
		n += proto.SizeVarint(121<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_GetRequest:
		s := proto.Size(x.GetRequest)
		n += proto.SizeVarint(130<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_GetResponse:
		s := proto.Size(x.GetResponse)
		n += proto.SizeVarint(131<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_GetNotification:
		s := proto.Size(x.GetNotification)
		n += proto.SizeVarint(132<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_InventoryRequest:
		s := proto.Size(x.InventoryRequest)
		n += proto.SizeVarint(140<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_InventoryResponse:
		s := proto.Size(x.InventoryResponse)
		n += proto.SizeVarint(141<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LoginRequest:
		s := proto.Size(x.LoginRequest)
		n += proto.SizeVarint(150<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LoginResponse:
		s := proto.Size(x.LoginResponse)
		n += proto.SizeVarint(151<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LogoutRequest:
		s := proto.Size(x.LogoutRequest)
		n += proto.SizeVarint(160<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LogoutResponse:
		s := proto.Size(x.LogoutResponse)
		n += proto.SizeVarint(161<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LookRequest:
		s := proto.Size(x.LookRequest)
		n += proto.SizeVarint(170<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LookResponse:
		s := proto.Size(x.LookResponse)
		n += proto.SizeVarint(171<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LookNotification:
		s := proto.Size(x.LookNotification)
		n += proto.SizeVarint(172<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_MoveRequest:
		s := proto.Size(x.MoveRequest)
		n += proto.SizeVarint(180<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_MoveResponse:
		s := proto.Size(x.MoveResponse)
		n += proto.SizeVarint(181<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_EnterRoomNotification:
		s := proto.Size(x.EnterRoomNotification)
		n += proto.SizeVarint(182<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_LeaveRoomNotification:
		s := proto.Size(x.LeaveRoomNotification)
		n += proto.SizeVarint(183<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_SayRequest:
		s := proto.Size(x.SayRequest)
		n += proto.SizeVarint(190<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_SayResponse:
		s := proto.Size(x.SayResponse)
		n += proto.SizeVarint(191<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_SayNotification:
		s := proto.Size(x.SayNotification)
		n += proto.SizeVarint(192<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_TellRequest:
		s := proto.Size(x.TellRequest)
		n += proto.SizeVarint(200<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_TellResponse:
		s := proto.Size(x.TellResponse)
		n += proto.SizeVarint(201<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_TellNotification:
		s := proto.Size(x.TellNotification)
		n += proto.SizeVarint(202<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_TellAllRequest:
		s := proto.Size(x.TellAllRequest)
		n += proto.SizeVarint(210<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_TellAllResponse:
		s := proto.Size(x.TellAllResponse)
		n += proto.SizeVarint(211<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_TellAllNotification:
		s := proto.Size(x.TellAllNotification)
		n += proto.SizeVarint(212<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_WhoRequest:
		s := proto.Size(x.WhoRequest)
		n += proto.SizeVarint(220<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GameMessage_WhoResponse:
		s := proto.Size(x.WhoResponse)
		n += proto.SizeVarint(221<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DropRequest struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
}

func (m *DropRequest) Reset()                    { *m = DropRequest{} }
func (m *DropRequest) String() string            { return proto.CompactTextString(m) }
func (*DropRequest) ProtoMessage()               {}
func (*DropRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DropRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type DropResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
}

func (m *DropResponse) Reset()                    { *m = DropResponse{} }
func (m *DropResponse) String() string            { return proto.CompactTextString(m) }
func (*DropResponse) ProtoMessage()               {}
func (*DropResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DropResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DropResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

type DropNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	PlayerName string `protobuf:"bytes,3,opt,name=playerName" json:"playerName,omitempty"`
	Target     string `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
}

func (m *DropNotification) Reset()                    { *m = DropNotification{} }
func (m *DropNotification) String() string            { return proto.CompactTextString(m) }
func (*DropNotification) ProtoMessage()               {}
func (*DropNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DropNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DropNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *DropNotification) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *DropNotification) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ErrorRequest struct {
	Error string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
}

func (m *ErrorRequest) Reset()                    { *m = ErrorRequest{} }
func (m *ErrorRequest) String() string            { return proto.CompactTextString(m) }
func (*ErrorRequest) ProtoMessage()               {}
func (*ErrorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ErrorRequest) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ErrorResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Error      string `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *ErrorResponse) Reset()                    { *m = ErrorResponse{} }
func (m *ErrorResponse) String() string            { return proto.CompactTextString(m) }
func (*ErrorResponse) ProtoMessage()               {}
func (*ErrorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ErrorResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ErrorResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *ErrorResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type ExitsRequest struct {
}

func (m *ExitsRequest) Reset()                    { *m = ExitsRequest{} }
func (m *ExitsRequest) String() string            { return proto.CompactTextString(m) }
func (*ExitsRequest) ProtoMessage()               {}
func (*ExitsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ExitsResponse struct {
	Success    bool        `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string      `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	ExitInfo   []*ExitInfo `protobuf:"bytes,3,rep,name=exitInfo" json:"exitInfo,omitempty"`
}

func (m *ExitsResponse) Reset()                    { *m = ExitsResponse{} }
func (m *ExitsResponse) String() string            { return proto.CompactTextString(m) }
func (*ExitsResponse) ProtoMessage()               {}
func (*ExitsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ExitsResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ExitsResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *ExitsResponse) GetExitInfo() []*ExitInfo {
	if m != nil {
		return m.ExitInfo
	}
	return nil
}

type ExitInfo struct {
	Direction int32  `protobuf:"varint,1,opt,name=direction" json:"direction,omitempty"`
	RoomName  string `protobuf:"bytes,2,opt,name=roomName" json:"roomName,omitempty"`
}

func (m *ExitInfo) Reset()                    { *m = ExitInfo{} }
func (m *ExitInfo) String() string            { return proto.CompactTextString(m) }
func (*ExitInfo) ProtoMessage()               {}
func (*ExitInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ExitInfo) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *ExitInfo) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

type GetRequest struct {
	Targets []string `protobuf:"bytes,1,rep,name=targets" json:"targets,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetRequest) GetTargets() []string {
	if m != nil {
		return m.Targets
	}
	return nil
}

type GetResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

type GetNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	PlayerName string `protobuf:"bytes,3,opt,name=playerName" json:"playerName,omitempty"`
	Target     string `protobuf:"bytes,4,opt,name=target" json:"target,omitempty"`
}

func (m *GetNotification) Reset()                    { *m = GetNotification{} }
func (m *GetNotification) String() string            { return proto.CompactTextString(m) }
func (*GetNotification) ProtoMessage()               {}
func (*GetNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *GetNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *GetNotification) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *GetNotification) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type InventoryRequest struct {
}

func (m *InventoryRequest) Reset()                    { *m = InventoryRequest{} }
func (m *InventoryRequest) String() string            { return proto.CompactTextString(m) }
func (*InventoryRequest) ProtoMessage()               {}
func (*InventoryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type InventoryResponse struct {
	Success        bool                               `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode     string                             `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	InventoryItems []*InventoryResponse_InventoryItem `protobuf:"bytes,3,rep,name=inventoryItems" json:"inventoryItems,omitempty"`
}

func (m *InventoryResponse) Reset()                    { *m = InventoryResponse{} }
func (m *InventoryResponse) String() string            { return proto.CompactTextString(m) }
func (*InventoryResponse) ProtoMessage()               {}
func (*InventoryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *InventoryResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *InventoryResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *InventoryResponse) GetInventoryItems() []*InventoryResponse_InventoryItem {
	if m != nil {
		return m.InventoryItems
	}
	return nil
}

type InventoryResponse_InventoryItem struct {
	Id               string  `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ShortDescription string  `protobuf:"bytes,2,opt,name=shortDescription" json:"shortDescription,omitempty"`
	ObjectCategories []int32 `protobuf:"varint,3,rep,packed,name=objectCategories" json:"objectCategories,omitempty"`
}

func (m *InventoryResponse_InventoryItem) Reset()         { *m = InventoryResponse_InventoryItem{} }
func (m *InventoryResponse_InventoryItem) String() string { return proto.CompactTextString(m) }
func (*InventoryResponse_InventoryItem) ProtoMessage()    {}
func (*InventoryResponse_InventoryItem) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13, 0}
}

func (m *InventoryResponse_InventoryItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *InventoryResponse_InventoryItem) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *InventoryResponse_InventoryItem) GetObjectCategories() []int32 {
	if m != nil {
		return m.ObjectCategories
	}
	return nil
}

type LoginRequest struct {
	PlayerName string `protobuf:"bytes,1,opt,name=playerName" json:"playerName,omitempty"`
	Password   string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *LoginRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	PlayerName string `protobuf:"bytes,3,opt,name=playerName" json:"playerName,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *LoginResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LoginResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *LoginResponse) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type LogoutRequest struct {
	Cause string `protobuf:"bytes,1,opt,name=cause" json:"cause,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *LogoutRequest) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

type LogoutResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
}

func (m *LogoutResponse) Reset()                    { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()               {}
func (*LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *LogoutResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogoutResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

type LookRequest struct {
	ValueList []string `protobuf:"bytes,1,rep,name=valueList" json:"valueList,omitempty"`
}

func (m *LookRequest) Reset()                    { *m = LookRequest{} }
func (m *LookRequest) String() string            { return proto.CompactTextString(m) }
func (*LookRequest) ProtoMessage()               {}
func (*LookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *LookRequest) GetValueList() []string {
	if m != nil {
		return m.ValueList
	}
	return nil
}

type LookResponse struct {
	Success         bool             `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode      string           `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	RoomDescription *RoomDescription `protobuf:"bytes,3,opt,name=roomDescription" json:"roomDescription,omitempty"`
}

func (m *LookResponse) Reset()                    { *m = LookResponse{} }
func (m *LookResponse) String() string            { return proto.CompactTextString(m) }
func (*LookResponse) ProtoMessage()               {}
func (*LookResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *LookResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LookResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *LookResponse) GetRoomDescription() *RoomDescription {
	if m != nil {
		return m.RoomDescription
	}
	return nil
}

type LookNotification struct {
	Success         bool             `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode      string           `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	RoomDescription *RoomDescription `protobuf:"bytes,3,opt,name=roomDescription" json:"roomDescription,omitempty"`
}

func (m *LookNotification) Reset()                    { *m = LookNotification{} }
func (m *LookNotification) String() string            { return proto.CompactTextString(m) }
func (*LookNotification) ProtoMessage()               {}
func (*LookNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *LookNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LookNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *LookNotification) GetRoomDescription() *RoomDescription {
	if m != nil {
		return m.RoomDescription
	}
	return nil
}

type RoomDescription struct {
	Name        string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description string   `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Exits       string   `protobuf:"bytes,3,opt,name=exits" json:"exits,omitempty"`
	Players     []string `protobuf:"bytes,4,rep,name=players" json:"players,omitempty"`
	Objects     []string `protobuf:"bytes,5,rep,name=objects" json:"objects,omitempty"`
	Mobs        []string `protobuf:"bytes,6,rep,name=mobs" json:"mobs,omitempty"`
}

func (m *RoomDescription) Reset()                    { *m = RoomDescription{} }
func (m *RoomDescription) String() string            { return proto.CompactTextString(m) }
func (*RoomDescription) ProtoMessage()               {}
func (*RoomDescription) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RoomDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RoomDescription) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *RoomDescription) GetExits() string {
	if m != nil {
		return m.Exits
	}
	return ""
}

func (m *RoomDescription) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *RoomDescription) GetObjects() []string {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *RoomDescription) GetMobs() []string {
	if m != nil {
		return m.Mobs
	}
	return nil
}

type MoveRequest struct {
	Direction int32 `protobuf:"varint,1,opt,name=direction" json:"direction,omitempty"`
}

func (m *MoveRequest) Reset()                    { *m = MoveRequest{} }
func (m *MoveRequest) String() string            { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()               {}
func (*MoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *MoveRequest) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type MoveResponse struct {
	Success         bool             `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode      string           `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	RoomDescription *RoomDescription `protobuf:"bytes,3,opt,name=roomDescription" json:"roomDescription,omitempty"`
}

func (m *MoveResponse) Reset()                    { *m = MoveResponse{} }
func (m *MoveResponse) String() string            { return proto.CompactTextString(m) }
func (*MoveResponse) ProtoMessage()               {}
func (*MoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *MoveResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MoveResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *MoveResponse) GetRoomDescription() *RoomDescription {
	if m != nil {
		return m.RoomDescription
	}
	return nil
}

type EnterRoomNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
}

func (m *EnterRoomNotification) Reset()                    { *m = EnterRoomNotification{} }
func (m *EnterRoomNotification) String() string            { return proto.CompactTextString(m) }
func (*EnterRoomNotification) ProtoMessage()               {}
func (*EnterRoomNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *EnterRoomNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *EnterRoomNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *EnterRoomNotification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LeaveRoomNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Direction  int32  `protobuf:"varint,4,opt,name=direction" json:"direction,omitempty"`
}

func (m *LeaveRoomNotification) Reset()                    { *m = LeaveRoomNotification{} }
func (m *LeaveRoomNotification) String() string            { return proto.CompactTextString(m) }
func (*LeaveRoomNotification) ProtoMessage()               {}
func (*LeaveRoomNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *LeaveRoomNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LeaveRoomNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *LeaveRoomNotification) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LeaveRoomNotification) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

type Ping struct {
	Target string `protobuf:"bytes,1,opt,name=target" json:"target,omitempty"`
}

func (m *Ping) Reset()                    { *m = Ping{} }
func (m *Ping) String() string            { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()               {}
func (*Ping) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *Ping) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type Pong struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Target     string `protobuf:"bytes,3,opt,name=target" json:"target,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *Pong) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Pong) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *Pong) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type SayRequest struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *SayRequest) Reset()                    { *m = SayRequest{} }
func (m *SayRequest) String() string            { return proto.CompactTextString(m) }
func (*SayRequest) ProtoMessage()               {}
func (*SayRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *SayRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SayResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Value      string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *SayResponse) Reset()                    { *m = SayResponse{} }
func (m *SayResponse) String() string            { return proto.CompactTextString(m) }
func (*SayResponse) ProtoMessage()               {}
func (*SayResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *SayResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SayResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *SayResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SayNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Sender     string `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
	Value      string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *SayNotification) Reset()                    { *m = SayNotification{} }
func (m *SayNotification) String() string            { return proto.CompactTextString(m) }
func (*SayNotification) ProtoMessage()               {}
func (*SayNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *SayNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SayNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *SayNotification) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *SayNotification) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TellRequest struct {
	ReceiverPlayerName string `protobuf:"bytes,1,opt,name=receiverPlayerName" json:"receiverPlayerName,omitempty"`
	Value              string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *TellRequest) Reset()                    { *m = TellRequest{} }
func (m *TellRequest) String() string            { return proto.CompactTextString(m) }
func (*TellRequest) ProtoMessage()               {}
func (*TellRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *TellRequest) GetReceiverPlayerName() string {
	if m != nil {
		return m.ReceiverPlayerName
	}
	return ""
}

func (m *TellRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TellResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
}

func (m *TellResponse) Reset()                    { *m = TellResponse{} }
func (m *TellResponse) String() string            { return proto.CompactTextString(m) }
func (*TellResponse) ProtoMessage()               {}
func (*TellResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{32} }

func (m *TellResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TellResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

type TellNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Sender     string `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
	Value      string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *TellNotification) Reset()                    { *m = TellNotification{} }
func (m *TellNotification) String() string            { return proto.CompactTextString(m) }
func (*TellNotification) ProtoMessage()               {}
func (*TellNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{33} }

func (m *TellNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TellNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *TellNotification) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *TellNotification) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TellAllRequest struct {
	Value string `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
}

func (m *TellAllRequest) Reset()                    { *m = TellAllRequest{} }
func (m *TellAllRequest) String() string            { return proto.CompactTextString(m) }
func (*TellAllRequest) ProtoMessage()               {}
func (*TellAllRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{34} }

func (m *TellAllRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TellAllResponse struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
}

func (m *TellAllResponse) Reset()                    { *m = TellAllResponse{} }
func (m *TellAllResponse) String() string            { return proto.CompactTextString(m) }
func (*TellAllResponse) ProtoMessage()               {}
func (*TellAllResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{35} }

func (m *TellAllResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TellAllResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

type TellAllNotification struct {
	Success    bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	Sender     string `protobuf:"bytes,3,opt,name=sender" json:"sender,omitempty"`
	Value      string `protobuf:"bytes,4,opt,name=value" json:"value,omitempty"`
}

func (m *TellAllNotification) Reset()                    { *m = TellAllNotification{} }
func (m *TellAllNotification) String() string            { return proto.CompactTextString(m) }
func (*TellAllNotification) ProtoMessage()               {}
func (*TellAllNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{36} }

func (m *TellAllNotification) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *TellAllNotification) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *TellAllNotification) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *TellAllNotification) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WhoRequest struct {
}

func (m *WhoRequest) Reset()                    { *m = WhoRequest{} }
func (m *WhoRequest) String() string            { return proto.CompactTextString(m) }
func (*WhoRequest) ProtoMessage()               {}
func (*WhoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{37} }

type WhoResponse struct {
	Success    bool                      `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ResultCode string                    `protobuf:"bytes,2,opt,name=resultCode" json:"resultCode,omitempty"`
	PlayerInfo []*WhoResponse_PlayerInfo `protobuf:"bytes,3,rep,name=playerInfo" json:"playerInfo,omitempty"`
}

func (m *WhoResponse) Reset()                    { *m = WhoResponse{} }
func (m *WhoResponse) String() string            { return proto.CompactTextString(m) }
func (*WhoResponse) ProtoMessage()               {}
func (*WhoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38} }

func (m *WhoResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *WhoResponse) GetResultCode() string {
	if m != nil {
		return m.ResultCode
	}
	return ""
}

func (m *WhoResponse) GetPlayerInfo() []*WhoResponse_PlayerInfo {
	if m != nil {
		return m.PlayerInfo
	}
	return nil
}

type WhoResponse_PlayerInfo struct {
	PlayerName string `protobuf:"bytes,1,opt,name=playerName" json:"playerName,omitempty"`
	ZoneName   string `protobuf:"bytes,2,opt,name=zoneName" json:"zoneName,omitempty"`
	RoomName   string `protobuf:"bytes,3,opt,name=roomName" json:"roomName,omitempty"`
}

func (m *WhoResponse_PlayerInfo) Reset()                    { *m = WhoResponse_PlayerInfo{} }
func (m *WhoResponse_PlayerInfo) String() string            { return proto.CompactTextString(m) }
func (*WhoResponse_PlayerInfo) ProtoMessage()               {}
func (*WhoResponse_PlayerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{38, 0} }

func (m *WhoResponse_PlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *WhoResponse_PlayerInfo) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

func (m *WhoResponse_PlayerInfo) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func init() {
	proto.RegisterType((*GameMessage)(nil), "message.GameMessage")
	proto.RegisterType((*DropRequest)(nil), "message.DropRequest")
	proto.RegisterType((*DropResponse)(nil), "message.DropResponse")
	proto.RegisterType((*DropNotification)(nil), "message.DropNotification")
	proto.RegisterType((*ErrorRequest)(nil), "message.ErrorRequest")
	proto.RegisterType((*ErrorResponse)(nil), "message.ErrorResponse")
	proto.RegisterType((*ExitsRequest)(nil), "message.ExitsRequest")
	proto.RegisterType((*ExitsResponse)(nil), "message.ExitsResponse")
	proto.RegisterType((*ExitInfo)(nil), "message.ExitInfo")
	proto.RegisterType((*GetRequest)(nil), "message.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "message.GetResponse")
	proto.RegisterType((*GetNotification)(nil), "message.GetNotification")
	proto.RegisterType((*InventoryRequest)(nil), "message.InventoryRequest")
	proto.RegisterType((*InventoryResponse)(nil), "message.InventoryResponse")
	proto.RegisterType((*InventoryResponse_InventoryItem)(nil), "message.InventoryResponse.InventoryItem")
	proto.RegisterType((*LoginRequest)(nil), "message.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "message.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "message.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "message.LogoutResponse")
	proto.RegisterType((*LookRequest)(nil), "message.LookRequest")
	proto.RegisterType((*LookResponse)(nil), "message.LookResponse")
	proto.RegisterType((*LookNotification)(nil), "message.LookNotification")
	proto.RegisterType((*RoomDescription)(nil), "message.RoomDescription")
	proto.RegisterType((*MoveRequest)(nil), "message.MoveRequest")
	proto.RegisterType((*MoveResponse)(nil), "message.MoveResponse")
	proto.RegisterType((*EnterRoomNotification)(nil), "message.EnterRoomNotification")
	proto.RegisterType((*LeaveRoomNotification)(nil), "message.LeaveRoomNotification")
	proto.RegisterType((*Ping)(nil), "message.Ping")
	proto.RegisterType((*Pong)(nil), "message.Pong")
	proto.RegisterType((*SayRequest)(nil), "message.SayRequest")
	proto.RegisterType((*SayResponse)(nil), "message.SayResponse")
	proto.RegisterType((*SayNotification)(nil), "message.SayNotification")
	proto.RegisterType((*TellRequest)(nil), "message.TellRequest")
	proto.RegisterType((*TellResponse)(nil), "message.TellResponse")
	proto.RegisterType((*TellNotification)(nil), "message.TellNotification")
	proto.RegisterType((*TellAllRequest)(nil), "message.TellAllRequest")
	proto.RegisterType((*TellAllResponse)(nil), "message.TellAllResponse")
	proto.RegisterType((*TellAllNotification)(nil), "message.TellAllNotification")
	proto.RegisterType((*WhoRequest)(nil), "message.WhoRequest")
	proto.RegisterType((*WhoResponse)(nil), "message.WhoResponse")
	proto.RegisterType((*WhoResponse_PlayerInfo)(nil), "message.WhoResponse.PlayerInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MudComm service

type MudCommClient interface {
	// Client sends and receives messages from the game server.
	SendReceive(ctx context.Context, opts ...grpc.CallOption) (MudComm_SendReceiveClient, error)
}

type mudCommClient struct {
	cc *grpc.ClientConn
}

func NewMudCommClient(cc *grpc.ClientConn) MudCommClient {
	return &mudCommClient{cc}
}

func (c *mudCommClient) SendReceive(ctx context.Context, opts ...grpc.CallOption) (MudComm_SendReceiveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MudComm_serviceDesc.Streams[0], c.cc, "/message.MudComm/SendReceive", opts...)
	if err != nil {
		return nil, err
	}
	x := &mudCommSendReceiveClient{stream}
	return x, nil
}

type MudComm_SendReceiveClient interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ClientStream
}

type mudCommSendReceiveClient struct {
	grpc.ClientStream
}

func (x *mudCommSendReceiveClient) Send(m *GameMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mudCommSendReceiveClient) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MudComm service

type MudCommServer interface {
	// Client sends and receives messages from the game server.
	SendReceive(MudComm_SendReceiveServer) error
}

func RegisterMudCommServer(s *grpc.Server, srv MudCommServer) {
	s.RegisterService(&_MudComm_serviceDesc, srv)
}

func _MudComm_SendReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MudCommServer).SendReceive(&mudCommSendReceiveServer{stream})
}

type MudComm_SendReceiveServer interface {
	Send(*GameMessage) error
	Recv() (*GameMessage, error)
	grpc.ServerStream
}

type mudCommSendReceiveServer struct {
	grpc.ServerStream
}

func (x *mudCommSendReceiveServer) Send(m *GameMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mudCommSendReceiveServer) Recv() (*GameMessage, error) {
	m := new(GameMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MudComm_serviceDesc = grpc.ServiceDesc{
	ServiceName: "message.MudComm",
	HandlerType: (*MudCommServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendReceive",
			Handler:       _MudComm_SendReceive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "message.proto",
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x58, 0xcb, 0x6f, 0x1b, 0x45,
	0x18, 0xcf, 0xc6, 0x4e, 0x93, 0x7e, 0xb6, 0x13, 0x77, 0xda, 0x94, 0x25, 0xaa, 0x4a, 0xb5, 0xd0,
	0x2a, 0x02, 0x11, 0xa1, 0x54, 0x42, 0x20, 0x10, 0x15, 0x7d, 0x28, 0x6e, 0x9b, 0x54, 0x61, 0x13,
	0xa9, 0x5c, 0x10, 0xda, 0xda, 0x53, 0x77, 0xc1, 0xde, 0x31, 0xbb, 0xeb, 0xb4, 0xa9, 0xc4, 0x85,
	0xf6, 0x58, 0x24, 0x4e, 0xc0, 0x11, 0x0e, 0x5c, 0x28, 0x47, 0x1e, 0x37, 0xe0, 0x08, 0x1c, 0x81,
	0x23, 0xfc, 0x0b, 0xfc, 0x0d, 0xe8, 0x9b, 0x99, 0xdd, 0xf9, 0x66, 0xbc, 0x45, 0xa8, 0x86, 0xf6,
	0xe6, 0xef, 0xfd, 0x9c, 0xf1, 0x6f, 0x16, 0x5a, 0x43, 0x9e, 0x65, 0x51, 0x9f, 0xaf, 0x8d, 0x52,
	0x91, 0x0b, 0x36, 0xaf, 0xc9, 0xe0, 0x3e, 0x83, 0xc6, 0x46, 0x34, 0xe4, 0x5b, 0x8a, 0x66, 0x4f,
	0x43, 0x7d, 0x14, 0x27, 0x7d, 0x7f, 0xfd, 0x84, 0xb7, 0xda, 0x58, 0x6f, 0xad, 0x15, 0x66, 0xdb,
	0x71, 0xd2, 0xef, 0xcc, 0x84, 0x52, 0x28, 0x95, 0x44, 0xd2, 0xf7, 0x4f, 0xbb, 0x4a, 0x42, 0x2b,
	0x89, 0xa4, 0xcf, 0x5e, 0x82, 0x46, 0x2f, 0x15, 0xa3, 0x90, 0xbf, 0x37, 0xe6, 0x59, 0xee, 0xf7,
	0xa4, 0xee, 0x91, 0x52, 0xf7, 0xbc, 0x91, 0x75, 0x66, 0x42, 0xaa, 0xca, 0x5e, 0x81, 0xa6, 0x22,
	0xb3, 0x91, 0x48, 0x32, 0xee, 0x73, 0x69, 0xba, 0xec, 0x98, 0x2a, 0x61, 0x67, 0x26, 0xb4, 0x94,
	0xd9, 0x06, 0xb4, 0x91, 0xbe, 0x22, 0xf2, 0xf8, 0x7a, 0xdc, 0x8d, 0xf2, 0x58, 0x24, 0xfe, 0x75,
	0xe9, 0xe0, 0x49, 0xcb, 0x01, 0x55, 0xe8, 0xcc, 0x84, 0x13, 0x46, 0x98, 0x05, 0x4f, 0x53, 0x91,
	0x16, 0x05, 0x24, 0x4e, 0x16, 0x17, 0x88, 0x10, 0xb3, 0xa0, 0xca, 0xec, 0x35, 0x68, 0x69, 0x5a,
	0xd7, 0x20, 0xa4, 0xf5, 0x51, 0xd7, 0xba, 0x2c, 0xc2, 0x56, 0x97, 0xc1, 0x6f, 0xc5, 0x79, 0x56,
	0x04, 0xbf, 0xe5, 0x06, 0x27, 0x42, 0x19, 0x9c, 0xd0, 0x32, 0xb8, 0xa2, 0x75, 0xf0, 0x7d, 0x37,
	0x38, 0x95, 0xca, 0xe0, 0x94, 0xc1, 0x5e, 0x04, 0xe8, 0xf3, 0xbc, 0x08, 0xfd, 0x81, 0x27, 0xad,
	0x0f, 0x97, 0xd6, 0x1b, 0xa5, 0xac, 0x33, 0x13, 0x12, 0x4d, 0xf6, 0x32, 0x34, 0x24, 0xa5, 0xa3,
	0xde, 0xf1, 0x9c, 0x91, 0x6f, 0x18, 0x21, 0x8e, 0x9c, 0xe8, 0xb2, 0x0b, 0xb0, 0xd4, 0xe7, 0xb9,
	0x35, 0xb4, 0xbb, 0xca, 0xdc, 0xa7, 0xe6, 0xce, 0xd0, 0x5c, 0x1b, 0xd6, 0x81, 0x76, 0x9c, 0xec,
	0xf1, 0x24, 0x17, 0xe9, 0x7e, 0x91, 0xff, 0x3d, 0xcf, 0x99, 0xfe, 0x45, 0x47, 0x03, 0xa7, 0xef,
	0x5a, 0xb1, 0xcb, 0x70, 0x88, 0xf0, 0x74, 0x45, 0x1f, 0x2a, 0x57, 0x2b, 0x55, 0xae, 0xca, 0xba,
	0x26, 0xed, 0xd8, 0xab, 0xd0, 0x1c, 0x88, 0x7e, 0x9c, 0x14, 0x29, 0x7d, 0xec, 0x39, 0xe3, 0xdc,
	0x24, 0x52, 0x1c, 0x27, 0xd5, 0x66, 0x67, 0xa0, 0xa5, 0x69, 0x9d, 0xc6, 0x27, 0x9e, 0x33, 0xcf,
	0x4d, 0x2a, 0xc6, 0x79, 0x5a, 0xfa, 0xda, 0x81, 0x18, 0x97, 0x23, 0xfd, 0xac, 0xc2, 0x81, 0x11,
	0x6b, 0x07, 0x86, 0xc1, 0xce, 0xc2, 0x62, 0xc1, 0xd0, 0x29, 0x7c, 0xae, 0x3c, 0x3c, 0x31, 0xe1,
	0xa1, 0xcc, 0xc1, 0xb1, 0xc0, 0xe5, 0x18, 0x08, 0xf1, 0x6e, 0x91, 0xc2, 0x97, 0xee, 0x72, 0x6c,
	0x1a, 0x21, 0x2e, 0x07, 0xd1, 0x55, 0xed, 0x43, 0x52, 0x07, 0xbf, 0x3f, 0xd9, 0x3e, 0x23, 0x55,
	0xed, 0x33, 0x34, 0xee, 0x04, 0xd2, 0xd6, 0x6e, 0x7d, 0xe5, 0xee, 0xc4, 0xa6, 0xa3, 0x81, 0x3b,
	0xe1, 0x5a, 0x61, 0x09, 0x43, 0xb1, 0xc7, 0x8b, 0x12, 0xbe, 0x76, 0x4b, 0xd8, 0x32, 0x42, 0x2c,
	0x81, 0xe8, 0x62, 0x09, 0x8a, 0xd4, 0x25, 0x7c, 0xe3, 0x96, 0xb0, 0x45, 0xa4, 0x58, 0x02, 0xd5,
	0x66, 0x57, 0x61, 0x99, 0x27, 0x39, 0x4f, 0x43, 0x21, 0x86, 0x56, 0x1d, 0xdf, 0x2a, 0x37, 0xc7,
	0xcd, 0xc9, 0xae, 0x52, 0xeb, 0xcc, 0x84, 0xd5, 0xf6, 0xe8, 0x78, 0xc0, 0xa3, 0x3d, 0x3e, 0xe1,
	0xf8, 0x3b, 0xd7, 0xf1, 0x66, 0x95, 0x1a, 0x3a, 0xae, 0xb4, 0xc7, 0x2b, 0x24, 0x8b, 0xca, 0x23,
	0xf8, 0xbd, 0x7b, 0x85, 0xec, 0x44, 0xe4, 0xf0, 0x11, 0x4d, 0x6c, 0xb1, 0xa4, 0x74, 0x9b, 0x7e,
	0x70, 0x5b, 0xbc, 0x13, 0xd1, 0xa3, 0x46, 0x75, 0xf1, 0x0a, 0xc9, 0xa2, 0x7d, 0xab, 0x8a, 0x1f,
	0xdd, 0x2b, 0x64, 0xc7, 0x56, 0xc0, 0x2b, 0xc4, 0xb1, 0xc1, 0x0c, 0x72, 0x3e, 0x18, 0x14, 0xa9,
	0xff, 0xe4, 0x66, 0xb0, 0x6b, 0x84, 0x98, 0x01, 0xd1, 0xc5, 0x21, 0x2b, 0x52, 0x67, 0xff, 0xb3,
	0x3b, 0xe4, 0x5d, 0x22, 0xc5, 0x21, 0x53, 0x6d, 0xdc, 0x53, 0xa4, 0xad, 0x02, 0x7e, 0x71, 0xf7,
	0x74, 0xd7, 0xd1, 0xc0, 0x3d, 0x75, 0xad, 0xf0, 0xb8, 0x22, 0xef, 0x75, 0x53, 0xc5, 0xaf, 0xee,
	0x71, 0xdd, 0xb5, 0xe4, 0x78, 0x5c, 0x6d, 0x0b, 0xec, 0x66, 0xc9, 0xd1, 0xe5, 0xfc, 0xe6, 0x76,
	0x73, 0xd7, 0x56, 0xc0, 0x6e, 0x3a, 0x36, 0xec, 0x0d, 0x38, 0xac, 0x59, 0x56, 0x5d, 0xbf, 0x2b,
	0x57, 0xc7, 0x5c, 0x57, 0x4e, 0x69, 0x55, 0xb6, 0xb8, 0x5a, 0x37, 0x6f, 0x88, 0xa2, 0xb2, 0x3f,
	0xdc, 0xd5, 0xba, 0x5a, 0xca, 0x70, 0xb5, 0x8c, 0x26, 0x0e, 0x56, 0x52, 0xba, 0x9a, 0x3f, 0xdd,
	0xc1, 0x5e, 0x35, 0x42, 0x1c, 0x2c, 0xd1, 0x3d, 0x3b, 0x0f, 0x73, 0x71, 0x92, 0xf0, 0x34, 0x38,
	0x09, 0x0d, 0x82, 0x5b, 0xd8, 0x51, 0x38, 0x90, 0x47, 0x69, 0x9f, 0xe7, 0x3e, 0x3a, 0x3b, 0x18,
	0x6a, 0x2a, 0xe8, 0x40, 0x93, 0x62, 0x14, 0xe6, 0xc3, 0x7c, 0x36, 0xee, 0x76, 0x79, 0x96, 0x49,
	0xc5, 0x85, 0xb0, 0x20, 0xd9, 0x71, 0x80, 0x94, 0x67, 0xe3, 0x41, 0x7e, 0x4e, 0xf4, 0xb8, 0x3f,
	0x2b, 0xbd, 0x10, 0x4e, 0x70, 0xd7, 0x83, 0xb6, 0x8b, 0x56, 0x1e, 0xde, 0x1d, 0xca, 0x47, 0x83,
	0x68, 0x9f, 0xa7, 0x57, 0xa2, 0x21, 0xf7, 0x6b, 0x4a, 0x6e, 0x38, 0xa4, 0xa0, 0xba, 0x55, 0xd0,
	0x33, 0xd0, 0xa4, 0x70, 0x87, 0x1d, 0x81, 0x39, 0x89, 0x57, 0x74, 0xdd, 0x8a, 0x08, 0xde, 0x86,
	0x96, 0x05, 0x6b, 0xa6, 0x48, 0xb4, 0x0c, 0x50, 0xa3, 0x01, 0x16, 0xa1, 0x49, 0x81, 0x4f, 0x70,
	0x0b, 0x5a, 0x16, 0x94, 0x99, 0x22, 0xe0, 0xf3, 0xb0, 0x80, 0x20, 0xe8, 0x62, 0x72, 0x5d, 0xf8,
	0xb5, 0x13, 0xb5, 0xd5, 0xc6, 0xfa, 0x21, 0x0b, 0x2e, 0xa1, 0x20, 0x2c, 0x55, 0x82, 0xf3, 0xb0,
	0x50, 0x70, 0xd9, 0x31, 0x38, 0xd8, 0x8b, 0x53, 0xde, 0x95, 0x9b, 0x8d, 0x61, 0xe7, 0x42, 0xc3,
	0x60, 0x2b, 0xb0, 0x90, 0xe2, 0xed, 0x88, 0x0d, 0x57, 0x61, 0x4b, 0x3a, 0x38, 0x05, 0x60, 0xc0,
	0x14, 0x26, 0xaf, 0xda, 0x8d, 0xc9, 0xd7, 0x56, 0x0f, 0x86, 0x05, 0x19, 0x6c, 0x40, 0x83, 0x60,
	0xa7, 0x29, 0xd6, 0xe9, 0x8e, 0x07, 0x4b, 0x0e, 0x8c, 0x7a, 0x0c, 0xdb, 0xc4, 0xa0, 0xed, 0x62,
	0xb0, 0xe0, 0xd3, 0x59, 0x38, 0x34, 0x81, 0xa6, 0xa6, 0xc8, 0x6d, 0x1b, 0x16, 0x4b, 0x1c, 0x76,
	0x31, 0xe7, 0xc3, 0x4c, 0x4f, 0x75, 0xf5, 0xc1, 0xd8, 0xcd, 0x70, 0xd0, 0x20, 0x74, 0xec, 0x57,
	0x6e, 0x42, 0xcb, 0x52, 0x60, 0x8b, 0x30, 0x1b, 0xf7, 0xf4, 0x09, 0x98, 0x8d, 0x7b, 0xec, 0x59,
	0x68, 0x67, 0x37, 0x44, 0x9a, 0x9f, 0xe7, 0x59, 0x37, 0x8d, 0x47, 0x72, 0x1d, 0x54, 0x62, 0x13,
	0x7c, 0xd4, 0x15, 0xd7, 0xde, 0xe1, 0xdd, 0xfc, 0x5c, 0x94, 0xf3, 0xbe, 0x48, 0x63, 0xae, 0x12,
	0x9c, 0x0b, 0x27, 0xf8, 0xc1, 0x25, 0x68, 0x52, 0x7c, 0xe8, 0xb4, 0xdd, 0x9b, 0x68, 0xfb, 0x0a,
	0x2c, 0x8c, 0xa2, 0x2c, 0xbb, 0x29, 0xd2, 0x5e, 0xb1, 0x71, 0x05, 0x1d, 0xc4, 0xd0, 0xb2, 0xc0,
	0xe2, 0xff, 0x37, 0xfd, 0xe0, 0xa4, 0x0c, 0x45, 0x50, 0xe4, 0x11, 0x98, 0xeb, 0x46, 0xe3, 0xac,
	0x48, 0x59, 0x11, 0xc1, 0x25, 0x58, 0xb4, 0xb1, 0xe3, 0x14, 0xeb, 0xfd, 0x1c, 0x34, 0x08, 0x8c,
	0xc4, 0x83, 0xb9, 0x17, 0x0d, 0xc6, 0x7c, 0x33, 0xce, 0x72, 0x7d, 0xa4, 0x0c, 0x23, 0xb8, 0xe7,
	0x61, 0x5f, 0x09, 0x50, 0x7c, 0xf8, 0x56, 0x9c, 0x85, 0x25, 0x3c, 0xd3, 0x74, 0xf0, 0x35, 0xe7,
	0xbf, 0x32, 0xb4, 0xe5, 0xa1, 0x6b, 0x10, 0x7c, 0xe4, 0x41, 0xdb, 0x45, 0xa1, 0x8f, 0x39, 0xa5,
	0x2f, 0x3c, 0x58, 0x72, 0x94, 0x18, 0x83, 0x7a, 0x62, 0xd6, 0x4e, 0xfe, 0x66, 0x27, 0xa0, 0xd1,
	0x9b, 0xd8, 0x79, 0xca, 0x92, 0xd7, 0x39, 0x5e, 0xd4, 0xe5, 0x75, 0x8e, 0x04, 0x56, 0xa7, 0xf6,
	0x25, 0xf3, 0xeb, 0xea, 0xc2, 0xd3, 0x24, 0x4a, 0xd4, 0x31, 0xc8, 0xfc, 0x39, 0x25, 0xd1, 0x24,
	0xc6, 0x1f, 0x8a, 0x6b, 0x99, 0x7f, 0x40, 0xb2, 0xe5, 0x6f, 0x1c, 0x3b, 0x81, 0xde, 0xff, 0x7c,
	0x1f, 0xcb, 0xb1, 0x53, 0xb0, 0xfd, 0x98, 0x7b, 0xcc, 0x61, 0xb9, 0x12, 0xb3, 0x4f, 0x91, 0x56,
	0x31, 0xa2, 0x9a, 0x19, 0x11, 0x5e, 0xfc, 0xcb, 0x95, 0x10, 0xfe, 0xbf, 0x8d, 0x63, 0xf7, 0xbe,
	0xee, 0xf6, 0xfe, 0x38, 0xd4, 0xb7, 0xe3, 0xa4, 0xff, 0x40, 0xdc, 0xf4, 0x26, 0xd4, 0xb7, 0x45,
	0xd2, 0x9f, 0x22, 0x27, 0xe3, 0xb9, 0x66, 0x79, 0x0e, 0x00, 0xcc, 0x9b, 0x03, 0xd7, 0x51, 0xde,
	0x03, 0xc5, 0x4d, 0x24, 0x89, 0xe0, 0x2d, 0x68, 0x90, 0xe7, 0xc5, 0x74, 0xe0, 0x45, 0xb9, 0xaf,
	0x51, 0xf7, 0xfb, 0xb0, 0xe4, 0x3c, 0x3f, 0xa6, 0xab, 0x33, 0xe3, 0x49, 0x8f, 0x17, 0x00, 0x49,
	0x53, 0x26, 0x74, 0x9d, 0x86, 0xde, 0x81, 0x06, 0x79, 0xb6, 0xb0, 0x35, 0x60, 0x29, 0xef, 0xf2,
	0x78, 0x8f, 0xa7, 0xdb, 0xee, 0x1f, 0x49, 0x85, 0xc4, 0x38, 0x9d, 0xa5, 0x4e, 0x3b, 0xd0, 0xa4,
	0xef, 0x99, 0x29, 0xae, 0xed, 0xdb, 0xd0, 0x76, 0xdf, 0x35, 0x8f, 0xac, 0x35, 0xa7, 0x60, 0xd1,
	0x7e, 0x0b, 0x3d, 0x60, 0x39, 0x2e, 0xc3, 0x92, 0xf3, 0xdc, 0x99, 0xa2, 0xe0, 0xf7, 0xe1, 0x70,
	0xc5, 0x83, 0xe7, 0x91, 0xd5, 0xdc, 0x04, 0x30, 0xaf, 0xa4, 0xe0, 0x2f, 0x0f, 0x1a, 0xe4, 0xed,
	0x33, 0x45, 0x16, 0x67, 0x0a, 0x44, 0x40, 0x50, 0xf4, 0x53, 0x55, 0xef, 0xab, 0xb5, 0xed, 0x52,
	0x2d, 0x24, 0x26, 0x2b, 0x3d, 0x00, 0x23, 0xf9, 0x37, 0x38, 0xe7, 0xb6, 0x48, 0x38, 0x45, 0xd6,
	0x05, 0x6d, 0xa1, 0xee, 0x9a, 0x8d, 0xba, 0xd7, 0x2f, 0xc1, 0xfc, 0xd6, 0xb8, 0x77, 0x4e, 0x0c,
	0x87, 0xec, 0x0c, 0x34, 0x76, 0x78, 0xd2, 0x0b, 0xd5, 0xce, 0x33, 0xf2, 0xa9, 0xd2, 0x7c, 0x12,
	0x5f, 0xa9, 0xe4, 0x06, 0x33, 0xab, 0xde, 0x0b, 0xde, 0xb5, 0x03, 0xf2, 0x73, 0xfa, 0xe9, 0xbf,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x01, 0xd9, 0x48, 0xf9, 0x5f, 0x17, 0x00, 0x00,
}
